"""create organization, and space tables. update resource table

Revision ID: 7c4e434f39a6
Revises: 19575d611113
Create Date: 2026-07-15 08:10:51.591180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4e434f39a6'
down_revision: Union[str, Sequence[str], None] = '19575d611113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_owner_id'), 'organizations', ['owner_id'], unique=False)
    op.create_table('spaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spaces_organization_id'), 'spaces', ['organization_id'], unique=False)
    op.add_column('resources', sa.Column('type', sa.Enum('desk', 'room', 'equipment', name='resourcetype', native_enum=False), nullable=False))
    op.add_column('resources', sa.Column('capacity', sa.Integer(), nullable=False))
    op.add_column('resources', sa.Column('credit_cost_per_hour', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('resources', sa.Column('space_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_resources_space_id'), 'resources', ['space_id'], unique=False)
    op.create_foreign_key(None, 'resources', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_index(op.f('ix_resources_space_id'), table_name='resources')
    op.drop_column('resources', 'space_id')
    op.drop_column('resources', 'credit_cost_per_hour')
    op.drop_column('resources', 'capacity')
    op.drop_column('resources', 'type')
    op.drop_index(op.f('ix_spaces_organization_id'), table_name='spaces')
    op.drop_table('spaces')
    op.drop_index(op.f('ix_organizations_owner_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
